[ConfigEditor] Add pagination control to fix UI issues (#447)
## Description

<_Include a description of the change and why this change was made._>

Add pagination control to self.right_grid, which improves performance
and also fix some known UI issues

[Known UI Issues]
1. https://github.com/microsoft/mu_feature_config/issues/426
=> self.page_size = 500 can avoid this
In the current ConfigEditor layout, having more than 532 items causes
self.conf_canvas scroll region to
exceed 32768 pixels, resulting in improper UI display.

2. row out of bounds when row >= 9997 in add_config_item()
=> self.page_size = 500 can avoid this, since the max row = 500 * 2 +
2(header) - 1(0-based) = 1001
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1968, in
__call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
File "V:\Common\mu_feature_config\SetupDataPkg\Tools\ConfigEditor.py",
line 893, in on_config_page_select_change
    self.build_config_data_page(page_id)
File "V:\Common\mu_feature_config\SetupDataPkg\Tools\ConfigEditor.py",
line 973, in build_config_data_page
    self.add_config_item(item, row, self.page_cfg_map[page_id])
File "V:\Common\mu_feature_config\SetupDataPkg\Tools\ConfigEditor.py",
line 1655, in add_config_item
    widget.grid(
File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 2580, in
grid_configure
    self.tk.call(
_tkinter.TclError: row out of bounds

3. disp_list[0] and disp_list[1] seems to have duplicate names always
=> We can just display one of them as header

4. UI response is sometimes quite slow since build_config_data_page()
might be invoked frequently by:
- Search
- Select trees on the left
=> This does not decrease the number of times build_config_data_page()
is called.
But it improves the execution speed on big files if
build_config_data_page() only loads 500 items at a time

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

- Execute ConfigEditor.py and loads a Config XML file with more than 500
members in a struct

## Integration Instructions

N/A